name: Linux

on:
    push:
    pull_request:
    schedule:
    #Every Sunday at midnight
    - cron:  '0 0 * * 0'

env:
  NBR_CORE: 25

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu20.04", "alpine"]
        ILC_INSTALL_VERSION: ["v02-01-02"]
        INSTALL_MODE: ["LATEST"]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4  
    - name: Build docker image OS
      run: docker build --tag os --file Dockerfile.${{ matrix.OS }} .
    - name: Build docker base
      run: docker build --file Dockerfile.base --tag base --build-arg image=os --build-arg compile_ncores=${{ env.NBR_CORE }} --build-arg ilcinstall_version=${{ matrix.ILC_INSTALL_VERSION }} --build-arg install_mode=${{ matrix.INSTALL_MODE }} .
